sudo: false

language: python

services:
  - docker

python:
  - "2.7"

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - python setup.py
